"""
List of words for the game
"""
word_list = ["Marko", "Damir", "pajama", "peekaboo", "phlegm",
             "pixel", "pizazz", "pneumonia", "polka", "Brazil",
             "Japan", "Dublin", "India", "Luanda", "Zagreb"
             "grandtheftauto", "diablo", "minecraft",
             "sheep",
             "sheet",
             "shelf",
             "ship",
             "shirt",
             "shock",
             "disarm",
             "discover",
             "dislike",
             "divide",
             "double",
             "doubt",
             "drag",
             "wash",
             "waste",
             "watch",
             "water",
             "wave",
             "weigh",
             "welcome",
             "whine",
             "endurable",
             "energetic",
             "enormous",
             "entertaining",
             "enthusiastic",
             "envious",
             "equable",
             "equal",
             "beginner",
             "behave",
             "behavior",
             "belief",
             "believe",
             "bell",
             "belligerent",
             "bells",
             "belong",
             "beneficial",
             "bent",
             "berry",
             "berserk",
             "best",
             "better",
             "bewildered",
             "big",
             "bike",]
